spring.application.name=firstSpringBoot
management.endpoints.web.exposure.include=health,info,beans,mappings
# management.endpoints.web.exposure.include=* -to enable all the enpoints provided by actuator package
# management.endpoints.web.exposure.exclude -to exclude the endpoints from actuators which will give 404 not found
management.info.env.enabled=true
info.app.name=firstSpringBoot
info.app.description=my first Spring boot application from practicing

# configuration for spring-boot-starter-security package which provides security for actuators endpoints
# Set a custom default username
spring.security.user.name=admin
# Set a custom default password
spring.security.user.password=admin

# testing property injection
test.name=Raghuveer
test.age=24

# spring boot native properties for logging
logging.file.name=my_crazy_shi.log
logging.file.path=~/SpringBoot/firstSpringBoot/mylogs
